"use strict";
/**
 * Phase 4 - Python<->Node parity suite (runs the Node scorer against the golden
 * reference generated by the Python oracle). FAILS (exit 1) if Node diverges
 * from the golden reference beyond the documented tolerances, so it is safe to
 * wire into CI.
 *
 * Tolerances (documented in the parity report; observed values are exact):
 *   prediction  : |Node - golden| <= 1e-3  (observed: 0)
 *   contributions: |Node - golden| <= 1.0  absolute per feature (observed: 0)
 *   base value  : <= 1e-3                  (observed: 0)
 *   round-to-cents and top-factor ranking must match exactly.
 */
const fs = require("fs");
const path = require("path");
const scorer = require("./scorer.js");

const ROOT = path.resolve(__dirname, "..");
const model = scorer.loadModel(
  path.join(ROOT, "models/deployed/tabular_model.json"),
  path.join(ROOT, "models/deployed/tabular_pipeline.json"),
);
const golden = JSON.parse(
  fs.readFileSync(path.join(ROOT, "reports/node_scorer/golden.json"), "utf8"),
);

const PRED_TOL = 1e-3;
const CONTRIB_TOL = 1.0;
const BASE_TOL = 1e-3;

let maxPred = 0, sumPred = 0, maxPredRel = 0;
let maxContrib = 0, sumContrib = 0, maxContribRel = 0;
let maxBase = 0;
let roundMismatch = 0;
let rankMismatch = 0;
const failed = [];

const ranking = (arr, positive, n) =>
  arr
    .map((v, i) => [i, v])
    .filter(([, v]) => (positive ? v > 0 : v < 0))
    .sort((a, b) => (positive ? b[1] - a[1] : a[1] - b[1]))
    .slice(0, n)
    .map(([i]) => i)
    .join(",");
const round2 = (v) => Math.round(v * 100) / 100;

for (const c of golden.cases) {
  const feats = scorer.engineerFeatures(c.input, model);
  const pred = scorer.predictRaw(model, feats);
  const r = scorer.predictContribs(model, feats);

  // prediction
  const absErr = Math.abs(pred - c.prediction_raw);
  maxPred = Math.max(maxPred, absErr);
  sumPred += absErr;
  maxPredRel = Math.max(maxPredRel, absErr / Math.max(1, Math.abs(c.prediction_raw)));
  if (absErr > PRED_TOL) failed.push({ id: c.id, kind: "prediction", diff: absErr });

  // contributions
  let cAbs = 0, cRel = 0;
  for (let i = 0; i < 33; i++) {
    const d = Math.abs(r.contribs[i] - c.shap_contribs[i]);
    cAbs = Math.max(cAbs, d);
    cRel = Math.max(cRel, d / Math.max(1, Math.abs(c.shap_contribs[i])));
    if (round2(r.contribs[i]) !== round2(c.shap_contribs[i])) roundMismatch++;
  }
  maxContrib = Math.max(maxContrib, cAbs);
  sumContrib += cAbs;
  maxContribRel = Math.max(maxContribRel, cRel);
  if (cAbs > CONTRIB_TOL) failed.push({ id: c.id, kind: "contribution", diff: cAbs });

  // base
  maxBase = Math.max(maxBase, Math.abs(r.base - c.shap_base));
  if (Math.abs(r.base - c.shap_base) > BASE_TOL) failed.push({ id: c.id, kind: "base", diff: Math.abs(r.base - c.shap_base) });

  // ranking parity
  if (
    ranking(r.contribs, true, 5) !== ranking(c.shap_contribs, true, 5) ||
    ranking(r.contribs, false, 5) !== ranking(c.shap_contribs, false, 5)
  ) {
    rankMismatch++;
    failed.push({ id: c.id, kind: "ranking" });
  }
}

const report = {
  generated: new Date().toISOString(),
  n_cases: golden.cases.length,
  canonical: {
    id: 0,
    input: golden.cases[0].input,
    expected_prediction: golden.cases[0].prediction,
    expected_prediction_raw: golden.cases[0].prediction_raw,
    node_prediction_raw: scorer.predictRaw(model, scorer.engineerFeatures(golden.cases[0].input, model)),
  },
  tolerances: { prediction: PRED_TOL, contribution: CONTRIB_TOL, base: BASE_TOL },
  prediction: {
    max_abs_error: maxPred,
    mean_abs_error: sumPred / golden.cases.length,
    max_relative_error: maxPredRel,
  },
  contributions: {
    max_abs_error: maxContrib,
    mean_abs_error: sumContrib / golden.cases.length,
    max_relative_error: maxContribRel,
    round_to_cents_mismatches: roundMismatch,
    top_factor_rank_mismatches: rankMismatch,
  },
  base: { max_abs_error: maxBase },
  failed_cases: failed,
};

const outPath = path.join(ROOT, "reports/node_scorer/parity_report.json");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(report, null, 2));
console.log("wrote", outPath);
console.log(`prediction max_abs=${maxPred} max_rel=${maxPredRel.toExponential(2)} mean_abs=${(sumPred / golden.cases.length).toExponential(2)}`);
console.log(`contrib max_abs=${maxContrib} mean_abs=${(sumContrib / golden.cases.length).toExponential(2)} round_mismatch=${roundMismatch} rank_mismatch=${rankMismatch}`);
console.log(`base max_abs=${maxBase} failures=${failed.length}`);

const ok =
  failed.length === 0 &&
  maxPred <= PRED_TOL &&
  maxContrib <= CONTRIB_TOL &&
  maxBase <= BASE_TOL &&
  roundMismatch === 0 &&
  rankMismatch === 0;
console.log(ok ? "PARITY: PASS" : "PARITY: FAIL");
process.exit(ok ? 0 : 1);